<li><a href="{{ url('anuncio/store') }}">Anúncio</a></li>
<li><a  href="{{ url('/profile') }}">Profile</a></li>
<li><a href="ad-post.html">ad post</a></li>
<li><a href="{{ url('/anuncio/meusanuncios/') }}">Meus Anúncios</a></li>
<li><a href="setting.html">settings</a></li>
<li><a href="bookmark.html">bookmarks</a></li>
<li><a href="message.html">message</a></li>
<li><a href="notification.html">notification</a></li>
<li><a href="user-form.html">logout</a></li>